# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

fib = [1,1]
sum = 0
while fib.last <= 4000000
  newest = fib.last + fib[-2]
  fib.push(newest)
  puts newest
  sum = sum + newest if newest.even? and newest <= 4000000
end

puts sum
